// <auto-generated />
using EPVBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPVBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250324205029_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EPVBackend.Model.Produit", b =>
                {
                    b.Property<string>("codeBarres")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codeBarres");

                    b.ToTable("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
